plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.12'
}

version = '0.1.0'

nextflowPlugin {
    nextflowVersion = '25.04.0'

    provider = 'VSC KU Leuven / UHasselt'
    className = 'io.vsc.kul.uhasselt.VscKulUhasseltPlugin'
    extensionPoints = [
        'io.vsc.kul.uhasselt.VscKulUhasseltExecutor',
    ]

    test {
        useJUnitPlatform()
        jvmArgs += [
            '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
            '--add-opens', 'java.base/java.security=ALL-UNNAMED',
        ]
    }
}

dependencies {
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
    testRuntimeOnly    'org.junit.platform:junit-platform-launcher:1.10.0'
}
